"""
Auto-generated test cases for CryptoKeySlot.
Generated by fix-package-implementation.py.
"""


from armodel import AUTOSAR
from armodel.models.M2.AUTOSARTemplates.AdaptivePlatform.PlatformModuleDeployment.CryptoDeployment.CryptoKeySlot import (
    CryptoKeySlot,
)


class TestCryptoKeySlot:
    """Test cases for CryptoKeySlot class."""


    def test_initialization(self):
        """Test initialization of CryptoKeySlot with proper attributes."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        assert obj.short_name == "test_cryptokeyslot"

    def test_get_allocateShadow(self):
        """Test getting allocateShadow."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        result = obj.getAllocateShadows()
        assert result == None

    def test_set_allocateShadow(self):
        """Test setting allocateShadow."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        test_value = None
        result = obj.setAllocateShadows(test_value)

        assert result == obj
        assert obj.getAllocateShadows() == test_value

    def test_get_cryptoAlgId(self):
        """Test getting cryptoAlgId."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        result = obj.getCryptoAlgIds()
        assert result == None

    def test_set_cryptoAlgId(self):
        """Test setting cryptoAlgId."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        test_value = None
        result = obj.setCryptoAlgIds(test_value)

        assert result == obj
        assert obj.getCryptoAlgIds() == test_value

    def test_get_cryptoObject(self):
        """Test getting cryptoObject."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        result = obj.getCryptoObjects()
        assert result == None

    def test_set_cryptoObject(self):
        """Test setting cryptoObject."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        test_value = None
        result = obj.setCryptoObjects(test_value)

        assert result == obj
        assert obj.getCryptoObjects() == test_value

    def test_get_keySlotAllowed(self):
        """Test getting keySlotAllowed."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        result = obj.getKeySlotAlloweds()
        assert result == None

    def test_set_keySlotAllowed(self):
        """Test setting keySlotAllowed."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        test_value = None
        result = obj.setKeySlotAlloweds(test_value)

        assert result == obj
        assert obj.getKeySlotAlloweds() == test_value

    def test_get_keySlotContent(self):
        """Test getting keySlotContent list."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        result = obj.getKeySlotContents()
        assert isinstance(result, list)

    def test_set_keySlotContent(self):
        """Test setting keySlotContent list."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        test_value = []
        result = obj.setKeySlotContents(test_value)

        assert result == obj
        assert obj.getKeySlotContents() == test_value

    def test_add_keySlotContent(self):
        """Test adding/creating keySlotContent."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        initial_count = len(obj.getKeySlotContents())
        # Test uses create method for owned attributes, add method for references
        attr_kind = 'attribute'
        is_ref = False
        should_use_create = (attr_kind == 'attribute' and not is_ref and True)

        if should_use_create:
            # For create method, use singular form of attribute name
            result = obj.createKeySlotContent("test_value")
            assert result is not None
        else:
            # For add method, also use singular form of attribute name
            result = obj.addKeySlotContent(None)
            assert result == obj
        assert len(obj.getKeySlotContents()) >= initial_count

    def test_get_slotCapacity(self):
        """Test getting slotCapacity."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        result = obj.getSlotCapacitys()
        assert result == None

    def test_set_slotCapacity(self):
        """Test setting slotCapacity."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        test_value = None
        result = obj.setSlotCapacitys(test_value)

        assert result == obj
        assert obj.getSlotCapacitys() == test_value

    def test_get_slotType(self):
        """Test getting slotType."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        result = obj.getSlotTypes()
        assert result == None

    def test_set_slotType(self):
        """Test setting slotType."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = CryptoKeySlot(ar_root, "test_cryptokeyslot")

        test_value = None
        result = obj.setSlotTypes(test_value)

        assert result == obj
        assert obj.getSlotTypes() == test_value

