"""
Auto-generated test cases for IdsmModuleInstantiation.
Generated by fix-package-implementation.py.
"""

import pytest

from armodel.models.M2.AUTOSARTemplates.AdaptivePlatform.PlatformModuleDeployment.IntrusionDetectionSystem.IdsmModuleInstantiation import IdsmModuleInstantiation
from armodel import AUTOSAR


class TestIdsmModuleInstantiation:
    """Test cases for IdsmModuleInstantiation class."""


    def test_initialization(self):
        """Test initialization of IdsmModuleInstantiation with proper attributes."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = IdsmModuleInstantiation(ar_root, "test_idsmmoduleinstantiation")

        assert obj.short_name == "test_idsmmoduleinstantiation"

