"""
Auto-generated test cases for IdsPlatformInstantiation.
Generated by fix-package-implementation.py.
"""

import pytest

from armodel.models.M2.AUTOSARTemplates.AdaptivePlatform.PlatformModuleDeployment.IntrusionDetectionSystem.IdsPlatformInstantiation import IdsPlatformInstantiation
from armodel import AUTOSAR


class TestIdsPlatformInstantiation:
    """Test cases for IdsPlatformInstantiation class."""


    def test_abstract_class_cannot_be_instantiated(self):
        """Test that IdsPlatformInstantiation is abstract and cannot be instantiated directly."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")

        with pytest.raises(TypeError) as err:
            obj = IdsPlatformInstantiation(ar_root, "test_idsplatforminstantiation")
        assert str(err.value) == "IdsPlatformInstantiation is an abstract class."

