import pytest

from armodel import AUTOSAR
from armodel.models.M2.AUTOSARTemplates.AdaptivePlatform.PlatformModuleDeployment.IntrusionDetectionSystem import IdsmModuleInstantiation, IdsPlatformInstantiation

"""
Auto-generated test cases for IdsPlatformInstantiation.
Generated by fix-package-implementation.py.
"""


class TestIdsPlatformInstantiation:
    """Test cases for IdsPlatformInstantiation class."""

    def test_abstract_class_cannot_be_instantiated(self):
        """Test that IdsPlatformInstantiation is abstract and cannot be instantiated directly."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")

        with pytest.raises(TypeError) as err:
            _obj = IdsPlatformInstantiation(ar_root, "test_idsplatforminstantiation")
        assert str(err.value) == "IdsPlatformInstantiation is an abstract class."


"""
Auto-generated test cases for IdsmModuleInstantiation.
Generated by fix-package-implementation.py.
"""


class TestIdsmModuleInstantiation:
    """Test cases for IdsmModuleInstantiation class."""

    def test_initialization(self):
        """Test initialization of IdsmModuleInstantiation with proper attributes."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = IdsmModuleInstantiation(ar_root, "test_idsmmoduleinstantiation")

        assert obj.short_name == "test_idsmmoduleinstantiation"
