"""
Auto-generated test cases for ModeInBswModuleDescriptionInstanceRef.
Generated by fix-package-implementation.py.
"""

import pytest

from armodel.models.M2.AUTOSARTemplates.BswModuleTemplate.BswOverview.InstanceRefs.ModeInBswModuleDescriptionInstanceRef import ModeInBswModuleDescriptionInstanceRef
from armodel import AUTOSAR


class TestModeInBswModuleDescriptionInstanceRef:
    """Test cases for ModeInBswModuleDescriptionInstanceRef class."""


    def test_initialization(self):
        """Test initialization of ModeInBswModuleDescriptionInstanceRef."""
        obj = ModeInBswModuleDescriptionInstanceRef()
        assert obj is not None

    def test_get_base(self):
        """Test getting base."""
        obj = ModeInBswModuleDescriptionInstanceRef()

        result = obj.getBases()
        assert result == None

    def test_set_base(self):
        """Test setting base."""
        obj = ModeInBswModuleDescriptionInstanceRef()

        test_value = None
        result = obj.setBases(test_value)

        assert result == obj
        assert obj.getBases() == test_value

    def test_get_contextMode(self):
        """Test getting contextMode."""
        obj = ModeInBswModuleDescriptionInstanceRef()

        result = obj.getContextModes()
        assert result == None

    def test_set_contextMode(self):
        """Test setting contextMode."""
        obj = ModeInBswModuleDescriptionInstanceRef()

        test_value = None
        result = obj.setContextModes(test_value)

        assert result == obj
        assert obj.getContextModes() == test_value

    def test_get_targetMode(self):
        """Test getting targetMode."""
        obj = ModeInBswModuleDescriptionInstanceRef()

        result = obj.getTargetModes()
        assert result == None

    def test_set_targetMode(self):
        """Test setting targetMode."""
        obj = ModeInBswModuleDescriptionInstanceRef()

        test_value = None
        result = obj.setTargetModes(test_value)

        assert result == obj
        assert obj.getTargetModes() == test_value

