from abc import ABC, abstractmethod
from typing import List, Optional, Dict, Any
from armodel.v2.models.M2.AUTOSARTemplates.GenericStructure.GeneralTemplateClasses.ArObject import ARObject

class ClientIdRange(ARObject):
    """
    With this element it is possible to restrict the Client Identifier of the
    transaction handle that is generated by the client RTE for inter-Ecu
    Client/Server communication to an allowed range of numerical values.
    
    Package: M2::AUTOSARTemplates::SystemTemplate::Fibex::FibexCore::CoreTopology::ClientIdRange
    
    Sources:
      - AUTOSAR_CP_TPS_SystemTemplate.pdf (Page 52, Classic Platform R23-11)
    """
    def __init__(self):
        super().__init__()

    # ===== Pythonic properties (CODING_RULE_V2_00016) =====
        # This specifies the lower limit of the ClientIdRange.
        self._lowerLimit: Optional["Limit"] = None

    @property
    def lower_limit(self) -> Optional["Limit"]:
        """Get lowerLimit (Pythonic accessor)."""
        return self._lowerLimit

    @lower_limit.setter
    def lower_limit(self, value: Optional["Limit"]) -> None:
        """
        Set lowerLimit with validation.
        
        Args:
            value: The lowerLimit to set
        
        Raises:
            TypeError: If value type is incorrect
        """
        if value is None:
            self._lowerLimit = None
            return

        if not isinstance(value, Limit):
            raise TypeError(
                f"lowerLimit must be Limit or None, got {type(value).__name__}"
            )
        self._lowerLimit = value
        # This specifies the upper limit of the ClientIdRange.
        self._upperLimit: Optional["Limit"] = None

    @property
    def upper_limit(self) -> Optional["Limit"]:
        """Get upperLimit (Pythonic accessor)."""
        return self._upperLimit

    @upper_limit.setter
    def upper_limit(self, value: Optional["Limit"]) -> None:
        """
        Set upperLimit with validation.
        
        Args:
            value: The upperLimit to set
        
        Raises:
            TypeError: If value type is incorrect
        """
        if value is None:
            self._upperLimit = None
            return

        if not isinstance(value, Limit):
            raise TypeError(
                f"upperLimit must be Limit or None, got {type(value).__name__}"
            )
        self._upperLimit = value

    # ===== AUTOSAR-compatible methods (delegate to properties) =====

    def getLowerLimit(self) -> "Limit":
        """
        AUTOSAR-compliant getter for lowerLimit.
        
        Returns:
            The lowerLimit value
        
        Note:
            Delegates to lower_limit property (CODING_RULE_V2_00017)
        """
        return self.lower_limit  # Delegates to property

    def setLowerLimit(self, value: "Limit") -> "ClientIdRange":
        """
        AUTOSAR-compliant setter for lowerLimit with method chaining.
        
        Args:
            value: The lowerLimit to set
        
        Returns:
            self for method chaining
        
        Note:
            Delegates to lower_limit property setter (gets validation automatically)
        """
        self.lower_limit = value  # Delegates to property setter
        return self

    def getUpperLimit(self) -> "Limit":
        """
        AUTOSAR-compliant getter for upperLimit.
        
        Returns:
            The upperLimit value
        
        Note:
            Delegates to upper_limit property (CODING_RULE_V2_00017)
        """
        return self.upper_limit  # Delegates to property

    def setUpperLimit(self, value: "Limit") -> "ClientIdRange":
        """
        AUTOSAR-compliant setter for upperLimit with method chaining.
        
        Args:
            value: The upperLimit to set
        
        Returns:
            self for method chaining
        
        Note:
            Delegates to upper_limit property setter (gets validation automatically)
        """
        self.upper_limit = value  # Delegates to property setter
        return self

    # ===== Fluent with_ methods (CODING_RULE_V2_00019) =====

    def with_lower_limit(self, value: Optional["Limit"]) -> "ClientIdRange":
        """
        Set lowerLimit and return self for chaining.
        
        Args:
            value: The lowerLimit to set
        
        Returns:
            self for method chaining
        
        Example:
            >>> obj.with_lower_limit("value")
        """
        self.lower_limit = value  # Use property setter (gets validation)
        return self

    def with_upper_limit(self, value: Optional["Limit"]) -> "ClientIdRange":
        """
        Set upperLimit and return self for chaining.
        
        Args:
            value: The upperLimit to set
        
        Returns:
            self for method chaining
        
        Example:
            >>> obj.with_upper_limit("value")
        """
        self.upper_limit = value  # Use property setter (gets validation)
        return self