"""
Auto-generated test cases for ApplicationDeferredDataType.
Generated by fix-package-implementation.py.
"""

import pytest

from armodel.models.M2.AUTOSARTemplates.AbstractPlatform.ApplicationDeferredDataType import ApplicationDeferredDataType
from armodel import AUTOSAR


class TestApplicationDeferredDataType:
    """Test cases for ApplicationDeferredDataType class."""

    def test_initialization(self):
        """Test initialization of ApplicationDeferredDataType with proper attributes."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationDeferredDataType(ar_root, "test_applicationdeferreddatatype")

        assert obj.short_name == "test_applicationdeferreddatatype"
