"""
Auto-generated test cases for ApplicationInterface.
Generated by fix-package-implementation.py.
"""


from armodel import AUTOSAR
from armodel.models.M2.AUTOSARTemplates.AbstractPlatform.ApplicationInterface import (
    ApplicationInterface,
)


class TestApplicationInterface:
    """Test cases for ApplicationInterface class."""

    def test_initialization(self):
        """Test initialization of ApplicationInterface with proper attributes."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        assert obj.short_name == "test_applicationinterface"

    def test_get_attribute(self):
        """Test getting attribute list."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        result = obj.getAttributes()
        assert isinstance(result, list)

    def test_set_attribute(self):
        """Test setting attribute list."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        test_value = []
        result = obj.setAttributes(test_value)

        assert result == obj
        assert obj.getAttributes() == test_value

    def test_add_attribute(self):
        """Test adding/creating attribute."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        initial_count = len(obj.getAttributes())
        # Test uses create method for owned attributes, add method for references
        attr_kind = 'attribute'
        is_ref = False
        should_use_create = (attr_kind == 'attribute' and not is_ref and False)

        if should_use_create:
            # For create method, use singular form of attribute name
            result = obj.createAttribute("test_value")
            assert result is not None
        else:
            # For add method, also use singular form of attribute name
            result = obj.addAttribute(None)
            assert result == obj
        assert len(obj.getAttributes()) >= initial_count

    def test_get_command(self):
        """Test getting command list."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        result = obj.getCommands()
        assert isinstance(result, list)

    def test_set_command(self):
        """Test setting command list."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        test_value = []
        result = obj.setCommands(test_value)

        assert result == obj
        assert obj.getCommands() == test_value

    def test_add_command(self):
        """Test adding/creating command."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        initial_count = len(obj.getCommands())
        # Test uses create method for owned attributes, add method for references
        attr_kind = 'attribute'
        is_ref = False
        should_use_create = (attr_kind == 'attribute' and not is_ref and False)

        if should_use_create:
            # For create method, use singular form of attribute name
            result = obj.createCommand("test_value")
            assert result is not None
        else:
            # For add method, also use singular form of attribute name
            result = obj.addCommand(None)
            assert result == obj
        assert len(obj.getCommands()) >= initial_count

    def test_get_indication(self):
        """Test getting indication list."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        result = obj.getIndications()
        assert isinstance(result, list)

    def test_set_indication(self):
        """Test setting indication list."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        test_value = []
        result = obj.setIndications(test_value)

        assert result == obj
        assert obj.getIndications() == test_value

    def test_add_indication(self):
        """Test adding/creating indication."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = ApplicationInterface(ar_root, "test_applicationinterface")

        initial_count = len(obj.getIndications())
        # Test uses create method for owned attributes, add method for references
        attr_kind = 'attribute'
        is_ref = True
        should_use_create = (attr_kind == 'attribute' and not is_ref and False)

        if should_use_create:
            # For create method, use singular form of attribute name
            result = obj.createIndication("test_value")
            assert result is not None
        else:
            # For add method, also use singular form of attribute name
            result = obj.addIndication(None)
            assert result == obj
        assert len(obj.getIndications()) >= initial_count
