"""
Auto-generated test cases for PlatformModuleEthernetEndpointConfiguration.
Generated by fix-package-implementation.py.
"""

import pytest

from armodel.models.M2.AUTOSARTemplates.AdaptivePlatform.PlatformModuleDeployment.AdaptiveModule.PlatformModuleEthernetEndpointConfiguration import PlatformModuleEthernetEndpointConfiguration
from armodel import AUTOSAR


class TestPlatformModuleEthernetEndpointConfiguration:
    """Test cases for PlatformModuleEthernetEndpointConfiguration class."""


    def test_initialization(self):
        """Test initialization of PlatformModuleEthernetEndpointConfiguration with proper attributes."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = PlatformModuleEthernetEndpointConfiguration(ar_root, "test_platformmoduleethernetendpointconfiguration")

        assert obj.short_name == "test_platformmoduleethernetendpointconfiguration"

    def test_get_communication(self):
        """Test getting communication."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = PlatformModuleEthernetEndpointConfiguration(ar_root, "test_platformmoduleethernetendpointconfiguration")

        result = obj.getCommunications()
        assert result == None

    def test_set_communication(self):
        """Test setting communication."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = PlatformModuleEthernetEndpointConfiguration(ar_root, "test_platformmoduleethernetendpointconfiguration")

        test_value = None
        result = obj.setCommunications(test_value)

        assert result == obj
        assert obj.getCommunications() == test_value

    def test_get_ipv4MulticastIp(self):
        """Test getting ipv4MulticastIp."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = PlatformModuleEthernetEndpointConfiguration(ar_root, "test_platformmoduleethernetendpointconfiguration")

        result = obj.getIpv4MulticastIps()
        assert result == None

    def test_set_ipv4MulticastIp(self):
        """Test setting ipv4MulticastIp."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = PlatformModuleEthernetEndpointConfiguration(ar_root, "test_platformmoduleethernetendpointconfiguration")

        test_value = None
        result = obj.setIpv4MulticastIps(test_value)

        assert result == obj
        assert obj.getIpv4MulticastIps() == test_value

    def test_get_ipv6MulticastIp(self):
        """Test getting ipv6MulticastIp."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = PlatformModuleEthernetEndpointConfiguration(ar_root, "test_platformmoduleethernetendpointconfiguration")

        result = obj.getIpv6MulticastIps()
        assert result == None

    def test_set_ipv6MulticastIp(self):
        """Test setting ipv6MulticastIp."""
        document = AUTOSAR.getInstance()
        ar_root = document.createARPackage("AUTOSAR")
        obj = PlatformModuleEthernetEndpointConfiguration(ar_root, "test_platformmoduleethernetendpointconfiguration")

        test_value = None
        result = obj.setIpv6MulticastIps(test_value)

        assert result == obj
        assert obj.getIpv6MulticastIps() == test_value

