# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

import os
import re
import sys

sys.path.insert(0, os.path.abspath('../src'))

from armodel import __version__

# -- Project information -----------------------------------------------------

project = 'py-armodel'
copyright = '2021-2026, melodypapa'
author = 'melodypapa'

# The full version, including alpha/beta/rc tags
release = __version__

# The short X.Y version
version = __version__

# Minimum Python version, read from pyproject.toml so it cannot drift from
# the packaging metadata.
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "pyproject.toml")) as _pyproject:
    _match = re.search(r'requires-python\s*=\s*">=([0-9.]+)"', _pyproject.read())
python_min = _match.group(1) if _match else "3.8"

# RST substitutions available to every document (|armodel_version|,
# |min_python|), so index.rst renders the real values instead of hardcoding
# them and going stale.
rst_prolog = (
    f".. |armodel_version| replace:: {release}\n"
    f".. |min_python| replace:: {python_min}\n"
)


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. they can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    'sphinx.ext.napoleon',
    'myst_parser',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
# The api/ directory holds the sphinx-apidoc generated stub pages. None of
# them are excluded: every generated stub is kept in the toctree so the full
# package tree is navigable in the sidebar. Package pages document only the
# members defined in their __init__.py (their automodule directives use
# ``:ignore-module-all:`` via the apidoc templates in _templates/apidoc/), so
# classes re-exported by a package are documented exactly once, on the page of
# the module that defines them — there are no duplicate object targets.
exclude_patterns = [
    '_build',
    'Thumbs.db',
    '.DS_Store',
    # Internal development notes that are not part of the published docs.
    'examples/*.md',
    'development',
    'plan',
    'requirements',
    'superpowers',
]

# 'autodoc.import_object' silences noise from autodoc probing module
# attributes. Deliberately NOT suppressing 'toc.not_included' / 'toc.excluded':
# every document must be reachable from the toctree (the ReadTheDocs sidebar),
# and those warnings are what flag a document that falls out of the tree.
suppress_warnings = ['autodoc.import_object']

# The suffix(es) of source filenames.
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx.
language = 'en'

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = None


# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = 'sphinx_rtd_theme'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'py-armodeldoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'py-armodel.tex', 'py-armodel Documentation',
     'melodypapa', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'py-armodel', 'py-armodel Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'py-armodel', 'py-armodel Documentation',
     author, 'py-armodel', 'Python library for AUTOSAR ARXML parsing and generation.',
     'Miscellaneous'),
]


# -- Options for Epub output -------------------------------------------------

# Bibliographic Dublin Core info.
epub_title = project

# The unique identifier of the text. This can be a ISBN number
# or the project homepage.
#
# epub_identifier = ''

# A unique identification for the text.
#
# epub_uid = ''

# A list of files that should not be packed into the epub file.
epub_exclude_files = ['search.html']


# -- Extension configuration -------------------------------------------------

# Autosummary generate stub pages
autosummary_generate = True

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Options for autodoc extension -------------------------------------------

# This value controls how to represent typehints
autodoc_typehints = 'description'

# This value controls what members are included by default
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'special-members': '__init__',
    'undoc-members': True,
    'exclude-members': '__weakref__'
}

# -- Options for napoleon extension ------------------------------------------

# Enable parsing of Google style docstrings
napoleon_google_docstring = True

# Enable parsing of NumPy style docstrings
napoleon_numpy_docstring = True

# Include private members (like _private_method) in the documentation
napoleon_include_private_with_doc = False

# Include special members (like __init__) in the documentation
napoleon_include_special_with_doc = True

# Use the .. admonition:: directive for the Example and Examples sections
napoleon_use_admonition_for_examples = False

# Use the .. admonition:: directive for the Note and Notes sections
napoleon_use_admonition_for_notes = False

# Use the .. admonition:: directive for the References and References sections
napoleon_use_admonition_for_references = False

# Use the .. admonition:: directive for the Todo and Todos sections
napoleon_use_admonition_for_todos = True
