from typing import List, Optional
from armodel.v2.models.M2.AUTOSARTemplates.GenericStructure.GeneralTemplateClasses.ARPackage import ARElement


class DltContext(ARElement):
    """
    This meta-class represents the Context that groups Log and Trace Messages
    that are generated by an application.

    Package: M2::AUTOSARTemplates::LogAndTraceExtract::DltContext

    Sources:
      - AUTOSAR_CP_TPS_SystemTemplate.pdf (Page 2017, Classic Platform R23-11)
      - AUTOSAR_FO_TPS_LogAndTraceExtract.pdf (Page 9, Foundation R23-11)
    """
    def __init__(self):
        super().__init__()

    # ===== Pythonic properties (CODING_RULE_V2_00016) =====
        # This attribute can be used to describe the contextId that is in the log and
        # trace message in more detail.
        self._context: Optional["String"] = None

    @property
    def context(self) -> Optional["String"]:
        """Get context (Pythonic accessor)."""
        return self._context

    @context.setter
    def context(self, value: Optional["String"]) -> None:
        """
        Set context with validation.

        Args:
            value: The context to set

        Raises:
            TypeError: If value type is incorrect
        """
        if value is None:
            self._context = None
            return

        if not isinstance(value, String):
            raise TypeError(
                f"context must be String or None, got {type(value).__name__}"
            )
        self._context = value
        # This attribute is used to group log and trace messages an application to
                # distinguish functionality.
        # 2090 Document ID 63: AUTOSAR_CP_TPS_SystemTemplate R23-11.
        self._contextId: Optional["String"] = None

    @property
    def context_id(self) -> Optional["String"]:
        """Get contextId (Pythonic accessor)."""
        return self._contextId

    @context_id.setter
    def context_id(self, value: Optional["String"]) -> None:
        """
        Set contextId with validation.

        Args:
            value: The contextId to set

        Raises:
            TypeError: If value type is incorrect
        """
        if value is None:
            self._contextId = None
            return

        if not isinstance(value, String):
            raise TypeError(
                f"contextId must be String or None, got {type(value).__name__}"
            )
        self._contextId = value
        # Group of Log and Trace Messages assigned to the Dlt atpVariation.
        self._dltMessage: List["DltMessage"] = []

    @property
    def dlt_message(self) -> List["DltMessage"]:
        """Get dltMessage (Pythonic accessor)."""
        return self._dltMessage

    # ===== AUTOSAR-compatible methods (delegate to properties) =====

    def getContext(self) -> "String":
        """
        AUTOSAR-compliant getter for context.

        Returns:
            The context value

        Note:
            Delegates to context property (CODING_RULE_V2_00017)
        """
        return self.context  # Delegates to property

    def setContext(self, value: "String") -> "DltContext":
        """
        AUTOSAR-compliant setter for context with method chaining.

        Args:
            value: The context to set

        Returns:
            self for method chaining

        Note:
            Delegates to context property setter (gets validation automatically)
        """
        self.context = value  # Delegates to property setter
        return self

    def getContextId(self) -> "String":
        """
        AUTOSAR-compliant getter for contextId.

        Returns:
            The contextId value

        Note:
            Delegates to context_id property (CODING_RULE_V2_00017)
        """
        return self.context_id  # Delegates to property

    def setContextId(self, value: "String") -> "DltContext":
        """
        AUTOSAR-compliant setter for contextId with method chaining.

        Args:
            value: The contextId to set

        Returns:
            self for method chaining

        Note:
            Delegates to context_id property setter (gets validation automatically)
        """
        self.context_id = value  # Delegates to property setter
        return self

    def getDltMessage(self) -> List["DltMessage"]:
        """
        AUTOSAR-compliant getter for dltMessage.

        Returns:
            The dltMessage value

        Note:
            Delegates to dlt_message property (CODING_RULE_V2_00017)
        """
        return self.dlt_message  # Delegates to property

    # ===== Fluent with_ methods (CODING_RULE_V2_00019) =====

    def with_context(self, value: Optional["String"]) -> "DltContext":
        """
        Set context and return self for chaining.

        Args:
            value: The context to set

        Returns:
            self for method chaining

        Example:
            >>> obj.with_context("value")
        """
        self.context = value  # Use property setter (gets validation)
        return self

    def with_context_id(self, value: Optional["String"]) -> "DltContext":
        """
        Set contextId and return self for chaining.

        Args:
            value: The contextId to set

        Returns:
            self for method chaining

        Example:
            >>> obj.with_context_id("value")
        """
        self.context_id = value  # Use property setter (gets validation)
        return self
